Rewrite CIS1 examples to CIS2
Concordium/concordium-rust-smart-contracts pull request #108
Opened 2022-05-18 06:29 UTC by limemloh

## Purpose

_Describe the purpose of the pull request, link to issue describing the problem, etc.

## Changes

_Describe the changes that were needed.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

2022-05-19 11:20 UTC, Bargsteen requested changes
Looks good in general. Needs a few tweaks as discussed 😊

2022-05-19 11:20 UTC, Bargsteen commented on examples/cis2-multi/src/lib.rs
> +                contract_name: OwnedContractName::new_unchecked(String::from("init_CIS2-Multi")),
Is this still needed?

2022-05-19 11:20 UTC, Bargsteen commented on examples/cis2-nft/src/lib.rs
>  /// - Any of the messages sent to contracts receiving a transfer choose to
Consider rephrasing this doc-comment to remove "messages" and "actions" as that terminology belongs to v0 contracts.

2022-05-19 11:20 UTC, Bargsteen commented on examples/cis2-nft/src/lib.rs
> +                contract_name: OwnedContractName::new_unchecked(String::from("init_CIS2-NFT")),
Is it still necessary to include the contract name? Wasn't that just for the callback?

2022-05-19 11:20 UTC, Bargsteen commented on examples/cis2-wccd/src/lib.rs
> +                contract_name: OwnedContractName::new_unchecked(String::from("init_CIS2-Multi")),
To be removed ;)

2022-05-22 16:43 UTC, abizjak approved these changes

2022-05-22 16:43 UTC, abizjak commented on examples/cis2-multi/src/lib.rs
> +/// Logs a `Transfer` event and invoke a receive hook function for every
```suggestion
/// Logs a `Transfer` event and invokes a receive hook function for every
```

2022-05-23 07:08 UTC, Bargsteen approved these changes

2022-05-23 07:08 UTC, Bargsteen commented on examples/cis2-wccd/src/lib.rs
> +/// Logs a `Transfer` event and invoke a receive hook function for every
```suggestion
/// Logs a `Transfer` event and invokes a receive hook function for every
```

2022-06-03 11:01 UTC, abizjak reviewed
I think overall it looks fine.

It would be useful to reduce the boilerplate a bit. Perhaps by using `derive_more` and adding a couple of macros to generate the implementations for serialization of token amounts (just normal macros, not procedural ones).

2022-06-03 11:01 UTC, abizjak commented on concordium-cis2/src/lib.rs
> +    fn get_type() -> schema::Type { schema::Type::Array(5, Box::new(schema::Type::U8)) }
Why is this a fixed array?

2022-06-03 13:47 UTC, limemloh commented on concordium-cis2/src/lib.rs
> +        }
I can add an issue for looking into this and/or add a comment in the code

2022-06-03 13:51 UTC, limemloh commented on concordium-cis2/src/lib.rs
> +    }
I know it was not exactly what you ment, but I have made macro with all the token amounts and thier implementations of basic operations.

2022-06-03 14:01 UTC, abizjak commented on concordium-cis2/src/lib.rs
> +        }
Add an issue, linking to this example of Wasm to make sure it is not forgotten.

2022-06-03 14:01 UTC, abizjak commented on concordium-cis2/src/lib.rs
> +    }
Looks good.

2022-06-03 14:01 UTC, abizjak commented on concordium-cis2/src/lib.rs
> +    fn get_type() -> schema::Type { schema::Type::Array(5, Box::new(schema::Type::U8)) }
Ok. Hopefully resolved very soon.

2022-06-03 14:01 UTC, abizjak approved these changes

2022-06-07 10:51 UTC, merged

2022-06-07 11:12 UTC, Bargsteen approved these changes
LGTM 👍

2022-06-07 11:12 UTC, Bargsteen commented on concordium-cis2/src/lib.rs
> +impl schema::SchemaType for OperatorUpdate {
Why was this implemented manually? 😊

2022-06-07 11:12 UTC, Bargsteen commented on concordium-cis2/src/lib.rs
> +impl schema::SchemaType for OperatorUpdate {
And all the ones below.